0x08-netowrking_basics_2

diff --git a/0x08-netowrking_basics_2/0-change_your_home_IP b/0x08-netowrking_basics_2/0-change_your_home_IP
--- a/0x08-netowrking_basics_2/0-change_your_home_IP
+++ b/0x08-netowrking_basics_2/0-change_your_home_IP
@@ -1,7 +1,23 @@
 #!/usr/bin/env bash
 # should changes domain resolve ips
 
-cp /etc/hosts ~/temp
-sed -i s/127.0.0.1/ ~/127.0.0.2/
-echo "8.8.8.8 facebook.com" >> ~/temp
-cp -f ~/temp /etc/hosts
+if [ "$EUID" -ne 0 ]; then
+    echo "This script must be run as root. Please use 'sudo'."
+    exit 1
+fi
+
+local="127.0.0.2 localhost"
+url="8.8.8.8 facebook.com"
+
+echo "$local" >> /etc/hosts
+echo "$url" >> /etc/hosts
+
+if grep -q "$local" /etc/hosts && grep -q "$url" /etc/hosts; then
+    echo "changed:"
+    cat /etc/hosts
+else
+    echo "error"
+    exit 1
+fi
+
+exit 0
